version: '3.4'

services:
  cicd:
    image: firmom/cicd
    environment:
      TZ: 'Europe/Warsaw'
    restart: always
    environment:
      # App settings and secrets
      - "APP_HOST=cicd.firmom.pl"
      - "APP_BASE_URL=http://cicd.firmom.pl"
      - "OAUTH_GITHUB_APP=Insert_your_app_id"
      - "OAUTH_GITHUB_SECRET=Insert_your_app_secret"

      # self-clean
      - "SLOT_SelfClean_SECRET_1=Insert_your_secret"

      # docker secrets
      - "DOCKER_PASSWORD_FILE=/docker-password"
      - "DOCKER_USERNAME=Insert_your_docker_username"
      - "DOCKER_PASSWORD=Insert_your_docker_passwrod"

      # firmom slots
      - "SLOT_BuildFirmomCentosDevtools_SECRET_1=Insert_your_secret"
      - "SLOT_BuildFirmomCICD_SECRET_1=Insert_your_secret"

      # gameinpl slots
      - "SLOT_BuildGameinplBeerpolyHome_SECRET_1=Insert_your_secret"
      - "SLOT_BuildGameinplBeerpoly_SECRET_1=Insert_your_secret"

      # gotcms slots
      - "SLOT_BuildGoatcmsEmptyapp_SECRET_1=Insert_your_secret"
      - "SLOT_BuildGoatcmsGoatcli_SECRET_1=Insert_your_secret"
      - "SLOT_BuildGoatcmsGoatcms_SECRET_1=Insert_your_secret"
      - "SLOT_BuildGoatcmsGoatcore_SECRET_1=Insert_your_secret"
      - "SLOT_BuildGoatcmsWebslots_SECRET_1=Insert_your_secret"

      # example users
      - "USER_1_USERNAME=Insert_Webslots_Account_Username"
      - "USER_1_LASTNAME=Insert_Webslots_Account_Lastname"
      - "USER_1_EMAIL=Insert_Webslots_Account_Email"
      - "USER_1_ROLES=Insert_Webslots_ACL_Roles_Like_superadmin"
      - "USER_1_CONNECT_GITHUB=Insert_Github_Account_Login"

      - "USER_2_USERNAME=Insert_Webslots_Account_Username"
      - "USER_2_LASTNAME=Insert_Webslots_Account_Lastname"
      - "USER_2_EMAIL=Insert_Webslots_Account_Email"
      - "USER_2_ROLES=Insert_Webslots_ACL_Roles_Like_superadmin"
      - "USER_2_CONNECT_GITHUB=Insert_Github_Account_Login"

      # Remote SSH keys
      - "REMOTE_DEPLOYMENT_MACHINE_SSH_PUB=Insert_Your_Remote_Deployment_Machine_Public_SSH_Key"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/dockerdata/firmom/cicd/data:/data"
      - "/dockerdata/firmom/cicd/ssh:/root/.ssh"
    ports:
      - 80:80
      - 1333:1333
      - 2077:2077
      - 2078:2078
      - 2079:2079

volumes:
  firmom-cicd-data:
