version: '3.4'

services:
  cicd:
    image: firmom/cicd:prod
    networks:
      - nproxy
    restart: always
    environment:
      - "TZ=Europe/Warsaw"
      - "CICD_CERT=Insert_your_cicd_certificate_directory_name"
      - "MODE=HTTPS"
      - "APP_HOST=Insert_your_cicd_host_like_cicd.firmom.com"
      - "APP_BASE_URL=Insert_your_cicd_baseurl_like_https://cicd.firmom.com"
      - "OAUTH_GITHUB_APP=Insert_your_github_oauth_app_id"
      - "OAUTH_GITHUB_SECRET=Insert_your_github_oauth_secret"

      # DevTools
      - "DEVTOOLS_SMTP_SERVER=Insert_smtp_server_for_all_devtools_desktop"
      - "DEVTOOLS_SMTP_USERNAME=Insert_smtp_username_for_all_devtools_desktop"
      - "DEVTOOLS_SMTP_PASSWORD=Insert_smtp_password_for_all_devtools_desktop"

      # Letsencrypt
      - "CERT_EMAIL=Insert_your_email_for_letsencrypt"

      # Deploy
      - "DEPLOY_DEV_REMOTE_USER=Insert_your_remote_user_name_to_deploy_app"
      - "DEPLOY_DEV_REMOTE_HOST=Insert_your_remote_host_to_deploy_app"

      - "DEPLOY_DEVTOOLS_REMOTE_USER=Insert_your_remote_user_name_to_deploy_devtools"
      - "DEPLOY_DEVTOOLS_REMOTE_HOST=Insert_your_remote_host_to_deploy_devtools"

      # DockerHUB secrets
      - "DOCKER_PASSWORD_FILE=/docker-password"
      - "DOCKER_USERNAME=Insert_your_dockerhub_password_to_deploy_app_image"
      - "DOCKER_PASSWORD=Insert_your_dockerhub_password_to_deploy_app_image"

      # NPM Token
      - "NPM_TOKEN=Insert_your_npm_token_to_publish_projects"

      # slots
      - "SLOT_BuildCentosDevtools_SECRET_1=Insert_your_secret"
      - "SLOT_BuildBeerpoly_SECRET_1=Insert_your_secret"
      - "SLOT_BuildFirmomCICD_SECRET_1=Insert_your_secret"
      - "SLOT_BuildGoatCLI_SECRET_1=Insert_your_secret"
      - "SLOT_BuildGoatCore_SECRET_1=Insert_your_secret"
      - "SLOT_BuildBeerpolyHome_SECRET_1=Insert_your_secret"
      - "SLOT_BuildGoatCMS_SECRET_1=Insert_your_secret"
      - "SLOT_BuildGoatCMSEmptyapp_SECRET_1=Insert_your_secret"
      - "SLOT_BuildWebslots_SECRET_1=Insert_your_secret"
      - "SLOT_BuildGoatJS_SECRET_1=Insert_your_secret"
      - "SLOT_BuildEventsPozogaEu_SECRET_1=Insert_your_secret"

      # Projects
      - "EVENTSPOZOGAEU_DB_USER=Insert_your_database_username"
      - "EVENTSPOZOGAEU_DB_PASS=Insert_your_database_password"
      - "EVENTSPOZOGAEU_DB_SNAPSHOT=/data/snapshots/latest.sql"
      - "EVENTSPOZOGAEU_WP_HOST=Insert_your_host"
      - "EVENTSPOZOGAEU_WP_USER_NAME=Insert_your_wordpress_username"
      - "EVENTSPOZOGAEU_WP_USER_PASS=Insert_your_wordpress_password"
      - "EVENTSPOZOGAEU_WP_USER_EMAIL=Insert_your_wordpress_email"

      # Users
      - "USER_1_USERNAME=Insert_user_name"
      - "USER_1_FIRSTNAME=Insert_first_name"
      - "USER_1_LASTNAME=Insert_last_name"
      - "USER_1_EMAIL=Insert_email"
      - "USER_1_ROLES=superadmin&admin"
      - "USER_1_PASSWORD=Insert_password"
      - "USER_1_CONNECT_GITHUB=Insert_github_name"
      - "USER_1_BASE_PORT=Insert_devtools_baseport"
      - "USER_1_VNC_RESOLUTION=Insert_VNC_resolution_for_remote_desktop"
      - "USER_1_VNC_COL_DEPTH=Insert_VNC_color_depth_for_remote_desktop"
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/dockerdata/firmom/cicd/data:/data"
      - "/dockerdata/firmom/cicd/ssh:/root/.ssh"
      - "/dockerdata/certs:/certs"
    ports:
      - 1333:443

networks:
  nproxy:
    external:
      name: nproxy
  default: