version: '3.4'

services:
  cicd:
    image: firmom/cicd:prod
    networks:
      - nproxy
    restart: always
    environment:
      - "TZ=Europe/Warsaw"
      - "MODE=HTTPS"
      - "APP_HOST=Insert_your_cicd_host_like_cicd.firmom.com"
      - "APP_BASE_URL=Insert_your_cicd_baseurl_like_https://cicd.firmom.com"
      - "OAUTH_GITHUB_APP=Insert_your_github_oauth_app_id"
      - "OAUTH_GITHUB_SECRET=Insert_your_github_oauth_secret"

      # Letsencrypt
      - "CERT_EMAIL=Insert_your_email_for_letsencrypt"

      # Deploy
      - "DEPLOY_DEV_REMOTE_USER=Insert_your_remote_user_name_to_deploy_app"
      - "DEPLOY_DEV_REMOTE_HOST=Insert_your_remote_host_to_deploy_app"

      # DockerHUB secrets
      - "DOCKER_PASSWORD_FILE=/docker-password"
      - "DOCKER_USERNAME=Insert_your_dockerhub_password_to_deploy_app_image"
      - "DOCKER_PASSWORD=Insert_your_dockerhub_password_to_deploy_app_image"

      # slots
      - "SLOT_BEERPOLY_SECRET_1=Insert_your_secret"
      - "SLOT_BEERPOLYHOME_SECRET_1=Insert_your_secret"
      - "SLOT_CENTOSDEVTOOLS_SECRET_1=Insert_your_secret"
      - "SLOT_FIRMOMCICD_SECRET_1=Insert_your_secret"
      - "SLOT_EVENTSPOZOGAEU_SECRET_1=Insert_your_secret"
      - "SLOT_GOATCLI_SECRET_1=Insert_your_secret"
      - "SLOT_GOATCMS_SECRET_1=Insert_your_secret"
      - "SLOT_GOATCMSEMPTYAPP_SECRET_1=Insert_your_secret"
      - "SLOT_GOATCORE_SECRET_1=Insert_your_secret"
      - "SLOT_WEBSLOTS_SECRET_1=Insert_your_secret"

      # Projects
      - "EVENTSPOZOGAEU_DB_USER=Insert_your_database_username"
      - "EVENTSPOZOGAEU_DB_PASS=Insert_your_database_password"
      - "EVENTSPOZOGAEU_DB_SNAPSHOT=/data/snapshots/latest.sql"
      - "EVENTSPOZOGAEU_WP_HOST=Insert_your_host"
      - "EVENTSPOZOGAEU_WP_USER_NAME=Insert_your_wordpress_username"
      - "EVENTSPOZOGAEU_WP_USER_PASS=Insert_your_wordpress_password"
      - "EVENTSPOZOGAEU_WP_USER_EMAIL=Insert_your_wordpress_email"

      # Users
      - "USER_1_USERNAME=Insert_user_name"
      - "USER_1_FIRSTNAME=Insert_first_name"
      - "USER_1_LASTNAME=Insert_last_name"
      - "USER_1_EMAIL=Insert_email"
      - "USER_1_ROLES=superadmin&admin"
      - "USER_1_PASSWORD=Insert_password"
      - "USER_1_CONNECT_GITHUB=Insert_github_name"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/dockerdata/firmom/cicd/data:/data"
      - "/dockerdata/firmom/cicd/ssh:/root/.ssh"
      - "/dockerdata/firmom/cicd/certs:/certs"
    ports:
      - 1333:443

networks:
  nproxy:
    external:
      name: nproxy
  default: